crud_project/urls.py
from django.contrib import admin
from django.urls import path
from crud.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('create/',create,name='create'),
    path('read/',read,name='read'),
    path('delete/<int:id>',delete,name='delete'),
    path('update/<int:id>',update,name='update'),
    path('updated/<int:id>/',updated,name='updated'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/models.py
from django.db import models
from django.utils import timezone

class Employee(models.Model):
    employee_name=models.CharField(max_length=40)
    employee_email=models.EmailField(max_length=30)
    employee_pic=models.FileField(upload_to='images/%Y/%m/%d')
    def __str__(self):
        return self.employee_name

crud/forms.py
from django import forms
from .models import Employee
choice=(
    ('telugu','Telugu'),
    ('hindi','Hindi'),
)
class EmployeeForm(forms.ModelForm):
    # lang=forms.MultipleChoiceField(choices=choice,widget=forms.CheckboxSelectMultiple())
    class Meta:
        model=Employee
        fields=('employee_name','employee_email','employee_pic')

crud/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import EmployeeForm
from .models import Employee
from django.contrib import messages
from  django.http import HttpResponse

def home(request):
    form=EmployeeForm()
    return render(request,'index.html',{'form':form})
def create(request):
    if request.method=='POST':
        form=EmployeeForm(request.POST ,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,"Added successfully")
    return redirect(read)

def read(request):
    emps=Employee.objects.all()
    return render(request,'result.html',{'emps':emps})
def delete(request,id):
    emps=Employee.objects.filter(id=id)
    emps.delete()
    return redirect(read)
def update(request,id):

    emps=Employee.objects.get(id=id)
    form=EmployeeForm(instance=emps)

    return render(request,'update.html',{'form':form,'emps':emps})

def updated(request,id):
    if request.method=='POST':
        instance=get_object_or_404(Employee,id=id)
        form=EmployeeForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            form.save()
            # Employee.objects.filter(id=id).update(form)
    return redirect(read)





templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        li {
                      list-style-type: none;
                                        }
    </style>
</head>
<body>

<form method="POST" action="{% url 'create' %}" id="new_user" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

</body>
<script type="text/javascript" src="js/script.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

{#<script type="text/javascript">#}
{#    $(document).on('submit','#new_user',function (e) {#}
{#        e.preventDefault();#}
{#        var form_data = new FormData();#}
{#        employee_name=$('#id_employee_name').val();#}
{#        employee_email=$('#id_employee_email').val();#}
{#        csrfmiddlewaretoken=$('input[name=csrfmiddlewaretoken]').val();#}
{#        var file_data = $("#id_employee_pic").prop("files")[0];#}
{#        form_data.append("file", file_data);#}
{#        form_data.append("employee_name", employee_name);#}
{#        form_data.append("employee_email", employee_email);#}
{#        form_data.append("csrfmiddlewaretoken", csrfmiddlewaretoken);#}
{#        $.ajax({#}
{#            type:'POST',#}
{#            url:'/create/',#}
{#            contentType:false,#}
{#            cache:false,#}
{#            processData:false,#}
{#            data:form_data,#}
{#            success:function (){#}
{#                alert("User Created Successfully");#}
{#            }#}
{#        });#}
{##}
{#    });#}
{#</script>#}

</html>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
{% endif %}
<table border="1">
    <tr>
        <th>EMP_ID</th>
        <th>EMP_NAME</th>
        <th>EMP_EMAIL</th>
        <th>EMP_PIC</th>
        <th colspan="2">OPERATION</th>
    </tr>
    {% for item in emps %}
        <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.employee_name }}</td>
        <td>{{ item.employee_email }}</td>
        <td><img src="{{ item.employee_pic.url }}" alt="image" height="20",width="30"></td>
        <td><a href="{% url 'delete' item.id %}">DELETE</a> </td>
        <td><a href="{% url 'update' item.id %}">UPDATE</a> </td>
        </tr>
    {% endfor %}
</table><br><br>
<a href="{% url 'home' %}"><button>ADD</button></a>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        li {
                      list-style-type: none;
                                        }
    </style>
</head>
<body>

<form method="POST" action="{% url 'updated' emps.id %}" id="new_user" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

</body>
<script type="text/javascript" src="js/script.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

{#<script type="text/javascript">#}
{#    $(document).on('submit','#new_user',function (e) {#}
{#        e.preventDefault();#}
{#        var form_data = new FormData();#}
{#        employee_name=$('#id_employee_name').val();#}
{#        employee_email=$('#id_employee_email').val();#}
{#        csrfmiddlewaretoken=$('input[name=csrfmiddlewaretoken]').val();#}
{#        var file_data = $("#id_employee_pic").prop("files")[0];#}
{#        form_data.append("file", file_data);#}
{#        form_data.append("employee_name", employee_name);#}
{#        form_data.append("employee_email", employee_email);#}
{#        form_data.append("csrfmiddlewaretoken", csrfmiddlewaretoken);#}
{#        $.ajax({#}
{#            type:'POST',#}
{#            url:'/create/',#}
{#            contentType:false,#}
{#            cache:false,#}
{#            processData:false,#}
{#            data:form_data,#}
{#            success:function (){#}
{#                alert("User Created Successfully");#}
{#            }#}
{#        });#}
{##}
{#    });#}
{#</script>#}

</html>